-- Agar purani table hai:
ALTER TABLE ToDoList ADD Priority TINYINT DEFAULT 2 NOT NULL;
ALTER TABLE ToDoList ADD CreatedDate DATETIME DEFAULT GETDATE() NULL;
ALTER TABLE ToDoList ADD DueDate DATETIME NULL;